services:
  jupyter:
    image: icculp/jupyter-ai-notebook
    container_name: jupyter
    shm_size: '16gb'
    ports:
      - "8888:8888"
    volumes:
      - ~/jupyter_data:/home/jovyan/work
      - ./jupyter_server_config.py:/home/jovyan/.jupyter/jupyter_server_config.py
      - ./lsp-settings.json:/home/jovyan/.jupyter/lsp-settings.json
      - conda_envs:/opt/conda/envs
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: >
      start-notebook.sh
        --NotebookApp.token=''
        --NotebookApp.password=''
        --ServerApp.iopub_data_rate_limit=10000000
    restart: unless-stopped
    networks:
      jupyter:
        ipv4_address: 192.168.34.10

volumes:
  conda_envs:

networks:
  jupyter:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.34.0/28